site_name: Henrique Wang - Applied Microeconomics | Natural Language Processing Researcher
site_url: https://henriqueyjw.github.io/site
site_description: Researcher in applied microeconomics and natural language processing, with a focus on analyzing the impact of public policies on economic outcomes.
site_author: Henrique Wang

theme:
  name: material
  language: en-US
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Modo escuro
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Modo claro
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight

nav:
  - Index: index.md
  - About Me: sobre.md
  - Papers: publicacoes.md
  - Presentations:
      - Workshops: projetos/workshops.md
      - Conferences: projetos/conferences.md
  - Contacts: contato.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/henriqueyjw
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/henrique-wang-68576544/
    - icon: fontawesome/solid/graduation-cap
      link: https://scholar.google.com/citations?user=h5vZYC0AAAAJ

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js